/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as FinishIdRouteImport } from './routes/finish.$id'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ValidateIdRouteImport } from './routes/validate.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishIdRoute = FinishIdRouteImport.update({
  id: '/finish/$id',
  path: '/finish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateIdRoute = ValidateIdRouteImport.update({
  id: '/validate/$id',
  path: '/validate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/setup': typeof SetupRoute
  '/finish/$id': typeof FinishIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/report/$id': typeof ReportIdRoute
  '/validate/$id': typeof ValidateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/setup': typeof SetupRoute
  '/finish/$id': typeof FinishIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/report/$id': typeof ReportIdRoute
  '/validate/$id': typeof ValidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/setup': typeof SetupRoute
  '/finish/$id': typeof FinishIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/report/$id': typeof ReportIdRoute
  '/validate/$id': typeof ValidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/setup'
    | '/finish/$id'
    | '/interview/$id'
    | '/report/$id'
    | '/validate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/setup'
    | '/finish/$id'
    | '/interview/$id'
    | '/report/$id'
    | '/validate/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/setup'
    | '/finish/$id'
    | '/interview/$id'
    | '/report/$id'
    | '/validate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  SetupRoute: typeof SetupRoute
  FinishIdRoute: typeof FinishIdRoute
  InterviewIdRoute: typeof InterviewIdRoute
  ReportIdRoute: typeof ReportIdRoute
  ValidateIdRoute: typeof ValidateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finish/$id': {
      id: '/finish/$id'
      path: '/finish/$id'
      fullPath: '/finish/$id'
      preLoaderRoute: typeof FinishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/$id': {
      id: '/validate/$id'
      path: '/validate/$id'
      fullPath: '/validate/$id'
      preLoaderRoute: typeof ValidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  SetupRoute: SetupRoute,
  FinishIdRoute: FinishIdRoute,
  InterviewIdRoute: InterviewIdRoute,
  ReportIdRoute: ReportIdRoute,
  ValidateIdRoute: ValidateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
